os: linux
dist: focal
language: node_js
node_js: node

jobs:
  include:
    - addons:
        chrome: "stable"
        firefox: "latest"
        apt:
          packages:
            - libnss3
      services:
        - xvfb
      before_install:
        - mkdir qunit
        - wget -O qunit/qunit-2.6.2.css http://code.jquery.com/qunit/qunit-2.6.2.css
        - wget -O qunit/qunit-2.6.2.js  http://code.jquery.com/qunit/qunit-2.6.2.js
        - npm install testem
        - ./node_modules/.bin/testem launchers

      script:
        - ./node_modules/.bin/testem --launch "Firefox,Headless Chrome" -t www/tests/qunit/run_tests.html ci

    - language: python
      python: 3.10
      before_install: pip install --upgrade pip
      before_script: pip install flake8
      script:
        # stop the build if there are Python syntax errors
        - flake8 . '--exclude=./.*,www/src/Lib/test/badsyntax_3131.py' --select=E999 --show-source --statistics
